//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenging_Challenges.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Achievements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Achievements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Challenging_Challenges.Resources.Achievements", typeof(Achievements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to solve a challenge 10 times.
        /// </summary>
        public static string Failed10 {
            get {
                return ResourceManager.GetString("Failed10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve challenge first.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve challenge with one attempt.
        /// </summary>
        public static string OneShot {
            get {
                return ResourceManager.GetString("OneShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post 10 challenges.
        /// </summary>
        public static string Posted10 {
            get {
                return ResourceManager.GetString("Posted10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post 100 challenges.
        /// </summary>
        public static string Posted100 {
            get {
                return ResourceManager.GetString("Posted100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post 25 challenges.
        /// </summary>
        public static string Posted25 {
            get {
                return ResourceManager.GetString("Posted25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post 5 challenges.
        /// </summary>
        public static string Posted5 {
            get {
                return ResourceManager.GetString("Posted5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post 50 challenges.
        /// </summary>
        public static string Posted50 {
            get {
                return ResourceManager.GetString("Posted50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn 10 rating points.
        /// </summary>
        public static string Rating10 {
            get {
                return ResourceManager.GetString("Rating10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn 100 rating points.
        /// </summary>
        public static string Rating100 {
            get {
                return ResourceManager.GetString("Rating100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn 25 rating points.
        /// </summary>
        public static string Rating25 {
            get {
                return ResourceManager.GetString("Rating25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn 5 rating points.
        /// </summary>
        public static string Rating5 {
            get {
                return ResourceManager.GetString("Rating5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn 50 rating points.
        /// </summary>
        public static string Rating50 {
            get {
                return ResourceManager.GetString("Rating50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve 10 challenges.
        /// </summary>
        public static string Solved10 {
            get {
                return ResourceManager.GetString("Solved10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve 100 challenges.
        /// </summary>
        public static string Solved100 {
            get {
                return ResourceManager.GetString("Solved100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve 25 challenges.
        /// </summary>
        public static string Solved25 {
            get {
                return ResourceManager.GetString("Solved25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve 5 challenges.
        /// </summary>
        public static string Solved5 {
            get {
                return ResourceManager.GetString("Solved5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve 50 challenges.
        /// </summary>
        public static string Solved50 {
            get {
                return ResourceManager.GetString("Solved50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become Top One!.
        /// </summary>
        public static string TopOne {
            get {
                return ResourceManager.GetString("TopOne", resourceCulture);
            }
        }
    }
}
